export const spokepoolAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_wrappedNativeTokenAddress',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_depositQuoteTimeBuffer',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: '_fillDeadlineBuffer',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'EMPTY_RELAYER',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'EMPTY_REPAYMENT_CHAIN_ID',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'INFINITE_FILL_DEADLINE',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_EXCLUSIVITY_PERIOD_SECONDS',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_TRANSFER_SIZE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'UPDATE_V3_DEPOSIT_DETAILS_HASH',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: '__SpokePool_init',
    inputs: [
      {
        name: '_initialDepositId',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: '_crossDomainAdmin',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_withdrawalRecipient',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'adminRemoveFunds',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'chainId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'crossDomainAdmin',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'originToken', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'relayerFeePct', type: 'int64', internalType: 'int64' },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'depositExclusive',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'inputToken', type: 'address', internalType: 'address' },
      { name: 'outputToken', type: 'address', internalType: 'address' },
      { name: 'inputAmount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'outputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'fillDeadline', type: 'uint32', internalType: 'uint32' },
      {
        name: 'exclusivityPeriod',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'depositFor',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'originToken', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'relayerFeePct', type: 'int64', internalType: 'int64' },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'depositQuoteTimeBuffer',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositV3',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'inputToken', type: 'address', internalType: 'address' },
      { name: 'outputToken', type: 'address', internalType: 'address' },
      { name: 'inputAmount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'outputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'fillDeadline', type: 'uint32', internalType: 'uint32' },
      {
        name: 'exclusivityParameter',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'depositV3Now',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'inputToken', type: 'address', internalType: 'address' },
      { name: 'outputToken', type: 'address', internalType: 'address' },
      { name: 'inputAmount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'outputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'fillDeadlineOffset',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'exclusivityPeriod',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'emergencyDeleteRootBundle',
    inputs: [
      { name: 'rootBundleId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'enabledDepositRoutes',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'executeRelayerRefundLeaf',
    inputs: [
      { name: 'rootBundleId', type: 'uint32', internalType: 'uint32' },
      {
        name: 'relayerRefundLeaf',
        type: 'tuple',
        internalType: 'struct SpokePoolInterface.RelayerRefundLeaf',
        components: [
          {
            name: 'amountToReturn',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'refundAmounts',
            type: 'uint256[]',
            internalType: 'uint256[]',
          },
          { name: 'leafId', type: 'uint32', internalType: 'uint32' },
          {
            name: 'l2TokenAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'refundAddresses',
            type: 'address[]',
            internalType: 'address[]',
          },
        ],
      },
      { name: 'proof', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'executeV3SlowRelayLeaf',
    inputs: [
      {
        name: 'slowFillLeaf',
        type: 'tuple',
        internalType: 'struct V3SpokePoolInterface.V3SlowFill',
        components: [
          {
            name: 'relayData',
            type: 'tuple',
            internalType: 'struct V3SpokePoolInterface.V3RelayData',
            components: [
              {
                name: 'depositor',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'recipient',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'exclusiveRelayer',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'inputToken',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'outputToken',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'inputAmount',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'outputAmount',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'originChainId',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'depositId',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'fillDeadline',
                type: 'uint32',
                internalType: 'uint32',
              },
              {
                name: 'exclusivityDeadline',
                type: 'uint32',
                internalType: 'uint32',
              },
              { name: 'message', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'updatedOutputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      { name: 'rootBundleId', type: 'uint32', internalType: 'uint32' },
      { name: 'proof', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fill',
    inputs: [
      { name: 'orderId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'originData', type: 'bytes', internalType: 'bytes' },
      { name: 'fillerData', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fillDeadlineBuffer',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'fillStatuses',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'fillV3Relay',
    inputs: [
      {
        name: 'relayData',
        type: 'tuple',
        internalType: 'struct V3SpokePoolInterface.V3RelayData',
        components: [
          {
            name: 'depositor',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'exclusiveRelayer',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'outputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'outputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'originChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'depositId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'fillDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'exclusivityDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'repaymentChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fillV3RelayWithUpdatedDeposit',
    inputs: [
      {
        name: 'relayData',
        type: 'tuple',
        internalType: 'struct V3SpokePoolInterface.V3RelayData',
        components: [
          {
            name: 'depositor',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'exclusiveRelayer',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'outputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'outputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'originChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'depositId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'fillDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'exclusivityDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'repaymentChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'updatedOutputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'updatedRecipient',
        type: 'address',
        internalType: 'address',
      },
      { name: 'updatedMessage', type: 'bytes', internalType: 'bytes' },
      {
        name: 'depositorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getCurrentTime',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUnsafeDepositId',
    inputs: [
      { name: 'msgSender', type: 'address', internalType: 'address' },
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'depositNonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      {
        name: '_initialDepositId',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: '_withdrawalRecipient',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'numberOfDeposits',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pauseDeposits',
    inputs: [{ name: 'pause', type: 'bool', internalType: 'bool' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pauseFills',
    inputs: [{ name: 'pause', type: 'bool', internalType: 'bool' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pausedDeposits',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pausedFills',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proxiableUUID',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'relayRootBundle',
    inputs: [
      {
        name: 'relayerRefundRoot',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'slowRelayRoot',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestV3SlowFill',
    inputs: [
      {
        name: 'relayData',
        type: 'tuple',
        internalType: 'struct V3SpokePoolInterface.V3RelayData',
        components: [
          {
            name: 'depositor',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'exclusiveRelayer',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'outputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'outputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'originChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'depositId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'fillDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'exclusivityDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rootBundles',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: 'slowRelayRoot',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'relayerRefundRoot',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setCrossDomainAdmin',
    inputs: [
      {
        name: 'newCrossDomainAdmin',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setEnableRoute',
    inputs: [
      { name: 'originToken', type: 'address', internalType: 'address' },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'enabled', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setWithdrawalRecipient',
    inputs: [
      {
        name: 'newWithdrawalRecipient',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'speedUpV3Deposit',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'depositId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'updatedOutputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'updatedRecipient',
        type: 'address',
        internalType: 'address',
      },
      { name: 'updatedMessage', type: 'bytes', internalType: 'bytes' },
      {
        name: 'depositorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tryMulticall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [
      {
        name: 'results',
        type: 'tuple[]',
        internalType: 'struct MultiCallerUpgradeable.Result[]',
        components: [
          { name: 'success', type: 'bool', internalType: 'bool' },
          { name: 'returnData', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unsafeDepositV3',
    inputs: [
      { name: 'depositor', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'inputToken', type: 'address', internalType: 'address' },
      { name: 'outputToken', type: 'address', internalType: 'address' },
      { name: 'inputAmount', type: 'uint256', internalType: 'uint256' },
      {
        name: 'outputAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'depositNonce',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'fillDeadline', type: 'uint32', internalType: 'uint32' },
      {
        name: 'exclusivityParameter',
        type: 'uint32',
        internalType: 'uint32',
      },
      { name: 'message', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'upgradeTo',
    inputs: [
      {
        name: 'newImplementation',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeToAndCall',
    inputs: [
      {
        name: 'newImplementation',
        type: 'address',
        internalType: 'address',
      },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdrawalRecipient',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'wrappedNativeToken',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract WETH9Interface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'AdminChanged',
    inputs: [
      {
        name: 'previousAdmin',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'newAdmin',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BeaconUpgraded',
    inputs: [
      {
        name: 'beacon',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EmergencyDeleteRootBundle',
    inputs: [
      {
        name: 'rootBundleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EnabledDepositRoute',
    inputs: [
      {
        name: 'originToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'enabled',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ExecutedRelayerRefundRoot',
    inputs: [
      {
        name: 'amountToReturn',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'chainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'refundAmounts',
        type: 'uint256[]',
        indexed: false,
        internalType: 'uint256[]',
      },
      {
        name: 'rootBundleId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'leafId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'l2TokenAddress',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'refundAddresses',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
      {
        name: 'caller',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FilledRelay',
    inputs: [
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalFilledAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'fillAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'repaymentChainId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'originChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'relayerFeePct',
        type: 'int64',
        indexed: false,
        internalType: 'int64',
      },
      {
        name: 'realizedLpFeePct',
        type: 'int64',
        indexed: false,
        internalType: 'int64',
      },
      {
        name: 'depositId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'destinationToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'relayer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'message',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: 'updatableRelayData',
        type: 'tuple',
        indexed: false,
        internalType: 'struct SpokePool.RelayExecutionInfo',
        components: [
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
          {
            name: 'relayerFeePct',
            type: 'int64',
            internalType: 'int64',
          },
          { name: 'isSlowRelay', type: 'bool', internalType: 'bool' },
          {
            name: 'payoutAdjustmentPct',
            type: 'int256',
            internalType: 'int256',
          },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FilledV3Relay',
    inputs: [
      {
        name: 'inputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'outputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'inputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'outputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'repaymentChainId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'originChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'fillDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'exclusivityDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'relayer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'message',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: 'relayExecutionInfo',
        type: 'tuple',
        indexed: false,
        internalType: 'struct V3SpokePoolInterface.V3RelayExecutionEventInfo',
        components: [
          {
            name: 'updatedRecipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'updatedMessage',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'updatedOutputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'fillType',
            type: 'uint8',
            internalType: 'enum V3SpokePoolInterface.FillType',
          },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FundsDeposited',
    inputs: [
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'originChainId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'relayerFeePct',
        type: 'int64',
        indexed: false,
        internalType: 'int64',
      },
      {
        name: 'depositId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'originToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'message',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PausedDeposits',
    inputs: [
      {
        name: 'isPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PausedFills',
    inputs: [
      {
        name: 'isPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RelayedRootBundle',
    inputs: [
      {
        name: 'rootBundleId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'relayerRefundRoot',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'slowRelayRoot',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RequestedSpeedUpDeposit',
    inputs: [
      {
        name: 'newRelayerFeePct',
        type: 'int64',
        indexed: false,
        internalType: 'int64',
      },
      {
        name: 'depositId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'updatedRecipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'updatedMessage',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: 'depositorSignature',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RequestedSpeedUpV3Deposit',
    inputs: [
      {
        name: 'updatedOutputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'updatedRecipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'updatedMessage',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: 'depositorSignature',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RequestedV3SlowFill',
    inputs: [
      {
        name: 'inputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'outputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'inputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'outputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'originChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'fillDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'exclusivityDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'message',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetWithdrawalRecipient',
    inputs: [
      {
        name: 'newWithdrawalRecipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetXDomainAdmin',
    inputs: [
      {
        name: 'newAdmin',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokensBridged',
    inputs: [
      {
        name: 'amountToReturn',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'chainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'leafId',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'l2TokenAddress',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'caller',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Upgraded',
    inputs: [
      {
        name: 'implementation',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'V3FundsDeposited',
    inputs: [
      {
        name: 'inputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'outputToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'inputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'outputAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'destinationChainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'quoteTimestamp',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'fillDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'exclusivityDeadline',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'exclusiveRelayer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'message',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'ClaimedMerkleLeaf', inputs: [] },
  { type: 'error', name: 'DepositsArePaused', inputs: [] },
  { type: 'error', name: 'DisabledRoute', inputs: [] },
  { type: 'error', name: 'ExpiredFillDeadline', inputs: [] },
  { type: 'error', name: 'FillsArePaused', inputs: [] },
  { type: 'error', name: 'InvalidChainId', inputs: [] },
  { type: 'error', name: 'InvalidCrossDomainAdmin', inputs: [] },
  { type: 'error', name: 'InvalidDepositorSignature', inputs: [] },
  { type: 'error', name: 'InvalidExclusiveRelayer', inputs: [] },
  { type: 'error', name: 'InvalidFillDeadline', inputs: [] },
  { type: 'error', name: 'InvalidMerkleLeaf', inputs: [] },
  { type: 'error', name: 'InvalidMerkleProof', inputs: [] },
  { type: 'error', name: 'InvalidPayoutAdjustmentPct', inputs: [] },
  { type: 'error', name: 'InvalidQuoteTimestamp', inputs: [] },
  { type: 'error', name: 'InvalidRelayerFeePct', inputs: [] },
  { type: 'error', name: 'InvalidSlowFillRequest', inputs: [] },
  { type: 'error', name: 'InvalidWithdrawalRecipient', inputs: [] },
  {
    type: 'error',
    name: 'LowLevelCallFailed',
    inputs: [{ name: 'data', type: 'bytes', internalType: 'bytes' }],
  },
  { type: 'error', name: 'MaxTransferSizeExceeded', inputs: [] },
  {
    type: 'error',
    name: 'MsgValueDoesNotMatchInputAmount',
    inputs: [],
  },
  { type: 'error', name: 'NoSlowFillsInExclusivityWindow', inputs: [] },
  { type: 'error', name: 'NotEOA', inputs: [] },
  { type: 'error', name: 'NotExclusiveRelayer', inputs: [] },
  { type: 'error', name: 'RelayFilled', inputs: [] },
  { type: 'error', name: 'WrongERC7683OrderId', inputs: [] },
] as const

export const wethAbi = [
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'DOMAIN_SEPARATOR',
    inputs: [],
    outputs: [{ name: 'result', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'spender', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'decimals',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonces',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'permit',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
      { name: 'v', type: 'uint8', internalType: 'uint8' },
      { name: 'r', type: 'bytes32', internalType: 'bytes32' },
      { name: 's', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transfer',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'spender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      {
        name: 'from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AllowanceOverflow', inputs: [] },
  { type: 'error', name: 'AllowanceUnderflow', inputs: [] },
  { type: 'error', name: 'ETHTransferFailed', inputs: [] },
  { type: 'error', name: 'InsufficientAllowance', inputs: [] },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
  { type: 'error', name: 'InvalidPermit', inputs: [] },
  {
    type: 'error',
    name: 'Permit2AllowanceIsFixedAtInfinity',
    inputs: [],
  },
  { type: 'error', name: 'PermitExpired', inputs: [] },
  { type: 'error', name: 'TotalSupplyOverflow', inputs: [] },
] as const

export const rhinestoneRelayerAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'fillBundle',
    inputs: [
      {
        name: 'executionDeposit',
        type: 'tuple',
        internalType: 'struct AcrossDeposit',
        components: [
          {
            name: 'inputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'outputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'outputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'destinationChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'originChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'depositId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'quoteTimestamp',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'fillDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'exclusivityDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'depositor',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'exclusiveRelayer',
            type: 'address',
            internalType: 'address',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'standardDeposits',
        type: 'tuple[]',
        internalType: 'struct AcrossDeposit[]',
        components: [
          {
            name: 'inputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'outputToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'inputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'outputAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'destinationChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'originChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'depositId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'quoteTimestamp',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'fillDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'exclusivityDeadline',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'depositor',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'exclusiveRelayer',
            type: 'address',
            internalType: 'address',
          },
          { name: 'message', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'repaymentChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multiCall',
    inputs: [
      {
        name: 'executions',
        type: 'tuple[]',
        internalType: 'struct Execution[]',
        components: [
          { name: 'to', type: 'address', internalType: 'address' },
          { name: 'value', type: 'uint256', internalType: 'uint256' },
          { name: 'data', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setSpokepool',
    inputs: [{ name: '_spokepool', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'spokepool',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract ISpokePool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawFunds',
    inputs: [
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
] as const

export const originModuleAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'orchestrator',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'resourceLock',
        type: 'address',
        internalType: 'contract IAccountLocker',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'SPOKEPOOL',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract ISpokePool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eip712Domain',
    inputs: [],
    outputs: [
      { name: 'fields', type: 'bytes1', internalType: 'bytes1' },
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'version', type: 'string', internalType: 'string' },
      { name: 'chainId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'verifyingContract',
        type: 'address',
        internalType: 'address',
      },
      { name: 'salt', type: 'bytes32', internalType: 'bytes32' },
      {
        name: 'extensions',
        type: 'uint256[]',
        internalType: 'uint256[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'handleAcross',
    inputs: [
      {
        name: 'payload',
        type: 'tuple[]',
        internalType: 'struct OriginModulePayload[]',
        components: [
          {
            name: 'order',
            type: 'tuple',
            internalType: 'struct Order',
            components: [
              {
                name: 'settlement',
                type: 'tuple',
                internalType: 'struct Settlement',
                components: [
                  {
                    name: 'orchestrator',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'recipient',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'settlementContract',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'targetChainId',
                    type: 'uint64',
                    internalType: 'uint64',
                  },
                  {
                    name: 'fillDeadline',
                    type: 'uint32',
                    internalType: 'uint32',
                  },
                  {
                    name: 'lastDepositId',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                ],
              },
              {
                name: 'acrossTransfer',
                type: 'tuple',
                internalType: 'struct AcrossTransfer',
                components: [
                  {
                    name: 'originModule',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'originAccount',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'targetAccount',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'originChainId',
                    type: 'uint64',
                    internalType: 'uint64',
                  },
                  {
                    name: 'initiateDeadline',
                    type: 'uint32',
                    internalType: 'uint32',
                  },
                  {
                    name: 'maxFee',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                  {
                    name: 'depositId',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                  {
                    name: 'originTransfer',
                    type: 'tuple',
                    internalType: 'struct TokenTransfer',
                    components: [
                      {
                        name: 'tokenAddress',
                        type: 'address',
                        internalType: 'address',
                      },
                      {
                        name: 'amount',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                    ],
                  },
                  {
                    name: 'targetTransfer',
                    type: 'tuple',
                    internalType: 'struct TokenTransfer',
                    components: [
                      {
                        name: 'tokenAddress',
                        type: 'address',
                        internalType: 'address',
                      },
                      {
                        name: 'amount',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'smartDigests',
                type: 'tuple',
                internalType: 'struct SmartDigest',
                components: [
                  {
                    name: 'acrossTransferDigests',
                    type: 'tuple',
                    internalType: 'struct IndexChainDigest',
                    components: [
                      {
                        name: 'digestIndex',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                      {
                        name: 'chainDataDigests',
                        type: 'bytes32[]',
                        internalType: 'bytes32[]',
                      },
                    ],
                  },
                  {
                    name: 'executionDigest',
                    type: 'bytes32',
                    internalType: 'bytes32',
                  },
                  {
                    name: 'userOpDigest',
                    type: 'bytes32',
                    internalType: 'bytes32',
                  },
                ],
              },
              { name: 'userSig', type: 'bytes', internalType: 'bytes' },
            ],
          },
          {
            name: 'auctionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'orchestratorSig',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'acrossMessagePayload',
            type: 'bytes',
            internalType: 'bytes',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'handleAcross',
    inputs: [
      {
        name: 'payload',
        type: 'tuple',
        internalType: 'struct OriginModulePayload',
        components: [
          {
            name: 'order',
            type: 'tuple',
            internalType: 'struct Order',
            components: [
              {
                name: 'settlement',
                type: 'tuple',
                internalType: 'struct Settlement',
                components: [
                  {
                    name: 'orchestrator',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'recipient',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'settlementContract',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'targetChainId',
                    type: 'uint64',
                    internalType: 'uint64',
                  },
                  {
                    name: 'fillDeadline',
                    type: 'uint32',
                    internalType: 'uint32',
                  },
                  {
                    name: 'lastDepositId',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                ],
              },
              {
                name: 'acrossTransfer',
                type: 'tuple',
                internalType: 'struct AcrossTransfer',
                components: [
                  {
                    name: 'originModule',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'originAccount',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'targetAccount',
                    type: 'address',
                    internalType: 'address',
                  },
                  {
                    name: 'originChainId',
                    type: 'uint64',
                    internalType: 'uint64',
                  },
                  {
                    name: 'initiateDeadline',
                    type: 'uint32',
                    internalType: 'uint32',
                  },
                  {
                    name: 'maxFee',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                  {
                    name: 'depositId',
                    type: 'uint256',
                    internalType: 'uint256',
                  },
                  {
                    name: 'originTransfer',
                    type: 'tuple',
                    internalType: 'struct TokenTransfer',
                    components: [
                      {
                        name: 'tokenAddress',
                        type: 'address',
                        internalType: 'address',
                      },
                      {
                        name: 'amount',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                    ],
                  },
                  {
                    name: 'targetTransfer',
                    type: 'tuple',
                    internalType: 'struct TokenTransfer',
                    components: [
                      {
                        name: 'tokenAddress',
                        type: 'address',
                        internalType: 'address',
                      },
                      {
                        name: 'amount',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'smartDigests',
                type: 'tuple',
                internalType: 'struct SmartDigest',
                components: [
                  {
                    name: 'acrossTransferDigests',
                    type: 'tuple',
                    internalType: 'struct IndexChainDigest',
                    components: [
                      {
                        name: 'digestIndex',
                        type: 'uint256',
                        internalType: 'uint256',
                      },
                      {
                        name: 'chainDataDigests',
                        type: 'bytes32[]',
                        internalType: 'bytes32[]',
                      },
                    ],
                  },
                  {
                    name: 'executionDigest',
                    type: 'bytes32',
                    internalType: 'bytes32',
                  },
                  {
                    name: 'userOpDigest',
                    type: 'bytes32',
                    internalType: 'bytes32',
                  },
                ],
              },
              { name: 'userSig', type: 'bytes', internalType: 'bytes' },
            ],
          },
          {
            name: 'auctionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'orchestratorSig',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'acrossMessagePayload',
            type: 'bytes',
            internalType: 'bytes',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'hashApprovalSpend',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct ApprovalSpend',
        components: [
          { name: 'account', type: 'address', internalType: 'address' },
          { name: 'token', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hashWithdrawRequest',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct WithdrawRequest',
        components: [
          { name: 'timestamp', type: 'uint32', internalType: 'uint32' },
          {
            name: 'tokenAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'orchestrator',
            type: 'address',
            internalType: 'address',
          },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'nonce', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initSpokePool',
    inputs: [
      {
        name: 'spokePool',
        type: 'address',
        internalType: 'contract ISpokePool',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isDepositIdValid',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'depositId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isInitialized',
    inputs: [
      { name: 'smartAccount', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isModuleType',
    inputs: [{ name: 'typeID', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'isUnlockNonceValid',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'onInstall',
    inputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onUninstall',
    inputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'registerApprovalSpend',
    inputs: [
      {
        name: 'approvalSpend',
        type: 'tuple',
        internalType: 'struct ApprovalSpend',
        components: [
          { name: 'account', type: 'address', internalType: 'address' },
          { name: 'token', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
      {
        name: 'orchestratorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setOmniLock',
    inputs: [
      {
        name: 'omniLock',
        type: 'tuple',
        internalType: 'struct OmniLock',
        components: [
          { name: 'account', type: 'address', internalType: 'address' },
          { name: 'enabled', type: 'bool', internalType: 'bool' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
      {
        name: 'orchestratorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unlockFundsForAccount',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'userSignature', type: 'bytes', internalType: 'bytes' },
      {
        name: 'orchestratorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct WithdrawRequest',
        components: [
          { name: 'timestamp', type: 'uint32', internalType: 'uint32' },
          {
            name: 'tokenAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'orchestrator',
            type: 'address',
            internalType: 'address',
          },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'nonce', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unlockFundsForAccount',
    inputs: [
      {
        name: 'orchestratorSignature',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct WithdrawRequest',
        components: [
          { name: 'timestamp', type: 'uint32', internalType: 'uint32' },
          {
            name: 'tokenAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'orchestrator',
            type: 'address',
            internalType: 'address',
          },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'nonce', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'verifyingContract',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'version',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'HandledDeposit',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ModuleInitialized',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SpokePoolInitialized',
    inputs: [
      {
        name: 'spokePool',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'weth',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AlreadyInitialized',
    inputs: [
      { name: 'smartAccount', type: 'address', internalType: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'AssetLocked',
    inputs: [
      { name: 'asset', type: 'address', internalType: 'address' },
      { name: 'lockedAmount', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { type: 'error', name: 'FeeExceedsAmount', inputs: [] },
  { type: 'error', name: 'InvalidAccount', inputs: [] },
  { type: 'error', name: 'InvalidAcrossPayload', inputs: [] },
  {
    type: 'error',
    name: 'InvalidAcrossTransferHash',
    inputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'InvalidAmountReceived', inputs: [] },
  { type: 'error', name: 'InvalidCallback', inputs: [] },
  { type: 'error', name: 'InvalidChainId', inputs: [] },
  { type: 'error', name: 'InvalidChainId', inputs: [] },
  { type: 'error', name: 'InvalidDepositId', inputs: [] },
  { type: 'error', name: 'InvalidInitialization', inputs: [] },
  { type: 'error', name: 'InvalidNonce', inputs: [] },
  { type: 'error', name: 'InvalidOrchestrator', inputs: [] },
  { type: 'error', name: 'InvalidOrchestratorSignature', inputs: [] },
  { type: 'error', name: 'InvalidOrderTarget', inputs: [] },
  { type: 'error', name: 'InvalidOriginAccount', inputs: [] },
  { type: 'error', name: 'InvalidOriginModule', inputs: [] },
  { type: 'error', name: 'InvalidSpokePool', inputs: [] },
  { type: 'error', name: 'InvalidTokenReceived', inputs: [] },
  { type: 'error', name: 'InvalidUserSignature', inputs: [] },
  {
    type: 'error',
    name: 'ModuleAlreadyInitialized',
    inputs: [
      { name: 'smartAccount', type: 'address', internalType: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'ModuleNotInitialized',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'NotInitialized',
    inputs: [
      { name: 'smartAccount', type: 'address', internalType: 'address' },
    ],
  },
  { type: 'error', name: 'NotInitializing', inputs: [] },
  { type: 'error', name: 'UserIntentExpired', inputs: [] },
  { type: 'error', name: 'UserOpFailed', inputs: [] },
] as const